name: Build_Container
env:
  owner: abook-presidio
  repo: securecontainer
on:
  repository_dispatch:
    types: [run-build]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkous Repository
        uses: actions/checkout/@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.BUCKET_KEY }}
          aws-secret-access-key: ${{ secrets.BUCKET_SECRET }}
          aws-region: us-east-1
